[package]
name = "bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pipe-parser = { path="../parser", features=["json"]}
clap = "2.33.3"