[package]
name = "bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pipe-parser = { path="../parser", features=["full"]}
clap = { version = "3.0.7", features = ["derive"] }
serde_derive = "1.0.115"
assert-type-eq = "0.1.0"
serde = "1.0.111"
regex = "1.4.1"
libloading = "0.7.3"
serde_json = "1.0.60"
pipe-core = { path = "../core", features = ["default"] }
chrono = "0.4.19"
log = "0.4.14"
