[workspace]
members = [
    "parser",
    "core",
    "runtime",
    "modules/payload",
    "modules/switch",
    "modules/http_server",
    "modules/request",
    "modules/dispatcher",
    "modules/log",
    "modules/link",
    "modules/exit",
    "modules/print",
    "extensions/sort",
]
