[workspace]
members = [
    "parser",
    "bin",
    "core",
    "modules/payload",
    "modules/switch",
    "modules/http_server",
    "modules/request",
    "modules/dispatcher",
    "modules/log"
]
