[config]
default_to_workspace = false

[tasks.example-modules]
command = "cargo"
args = ["run", "-p", "lab-runtime", "--release", "example/modules/main.lab"]

[tasks.example-order]
command = "cargo"
args = ["run", "-p", "lab-runtime", "--release", "example/order.lab"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.extensions-sync]
command = "cp"
args =  ["target/release/libextension_sort.so", "extensions/extension_sort.lrepos"]


[tasks.extensions-build]
command = "cargo"
args = ["build", "--release", "-p", "lab-extension-sort"]

[tasks.extensions]
run_task = { name = ["extensions-build", "extensions-sync"], parallel = false }


